import { PropertyProps } from "@/interfaces";

export const PROPERTYLISTINGSAMPLE: PropertyProps[] = [
  {
    name: "Villa Ocean Breeze",
    address: { state: "Seminyak", city: "Bali", country: "Indonesia" },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    price: 3200,
    offers: { bed: "3", shower: "3", occupants: "4-6" },
    image: "/Users/sirwanjohi/Desktop/ALX-ProDev/alx-listing-app-01/public/assets/apartment.jpg",
    discount: "",
    description:
      "Experience tropical paradise in this luxurious Bali villa with a private pool and breathtaking ocean breeze views.",
  },
  {
    name: "Mountain Escape Chalet",
    address: { state: "Aspen", city: "Colorado", country: "USA" },
    rating: 4.7,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: { bed: "4", shower: "2", occupants: "5-7" },
    image: "https://example.com/image2.jpg",
    discount: "30",
    description:
      "A cozy wooden chalet nestled in the Rockies with scenic mountain views and a warm fireplace for ultimate comfort.",
  },
  {
    name: "Cozy Desert Retreat",
    address: { state: "Palm Springs", city: "California", country: "USA" },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    price: 1500,
    offers: { bed: "2", shower: "1", occupants: "2-3" },
    image: "https://example.com/image3.jpg",
    discount: "",
    description:
      "Relax in this cozy desert retreat featuring modern design, scenic desert views, and pet-friendly accommodation.",
  },
  {
    name: "City Lights Penthouse",
    address: { state: "New York", city: "New York", country: "USA" },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    price: 4500,
    offers: { bed: "2", shower: "2", occupants: "2-4" },
    image: "https://example.com/image4.jpg",
    discount: "15",
    description:
      "Enjoy stunning skyline views from this luxurious New York penthouse with modern amenities and 24-hour access.",
  },
  {
    name: "Riverside Cabin",
    address: { state: "Queenstown", city: "Otago", country: "New Zealand" },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    price: 2800,
    offers: { bed: "3", shower: "2", occupants: "4-6" },
    image: "https://example.com/image5.jpg",
    discount: "20",
    description:
      "Stay in a peaceful riverside cabin surrounded by nature, with private dock access and complimentary kayaks.",
  },
  {
    name: "Modern Beachfront Villa",
    address: { state: "Sidemen", city: "Bali", country: "Indonesia" },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 5000,
    offers: { bed: "5", shower: "4", occupants: "8-10" },
    image: "https://example.com/image6.jpg",
    discount: "",
    description:
      "Step directly onto the beach from this modern villa with a private pool and personal chef service.",
  },
  {
    name: "Lakeside Chalet",
    address: { state: "Banff", city: "Alberta", country: "Canada" },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    price: 2300,
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: "https://example.com/image7.jpg",
    discount: "10",
    description:
      "Wake up to serene lake and mountain views in this beautiful Banff chalet near popular hiking trails.",
  },
  {
    name: "Tropical Garden Villa",
    address: { state: "Koh Samui", city: "Surat Thani", country: "Thailand" },
    rating: 4.8,
    category: ["Garden", "Free Parking", "Self Checkin"],
    price: 2750,
    offers: { bed: "3", shower: "3", occupants: "5-6" },
    image: "https://example.com/image8.jpg",
    discount: "25",
    description:
      "Immerse yourself in lush greenery and tropical vibes at this serene garden villa in Koh Samui.",
  },
  {
    name: "Urban Loft",
    address: { state: "Berlin", city: "Berlin", country: "Germany" },
    rating: 4.6,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    price: 2000,
    offers: { bed: "2", shower: "1", occupants: "2-3" },
    image: "https://example.com/image9.jpg",
    discount: "",
    description:
      "A modern loft apartment in the heart of Berlin, perfect for exploring art, culture, and nightlife.",
  },
  {
    name: "Secluded Forest Cabin",
    address: { state: "Whistler", city: "British Columbia", country: "Canada" },
    rating: 4.72,
    category: ["Secluded", "Hot Tub", "Self Checkin"],
    price: 2600,
    offers: { bed: "4", shower: "2", occupants: "5-7" },
    image: "https://example.com/image10.jpg",
    discount: "40",
    description:
      "Disconnect from the world in this secluded forest cabin, complete with a hot tub and cozy interiors.",
  },
  {
    name: "Cliffside Villa",
    address: { state: "Amalfi", city: "Salerno", country: "Italy" },
    rating: 4.93,
    category: ["Cliffside", "Infinity Pool", "Sea View"],
    price: 6000,
    offers: { bed: "4", shower: "4", occupants: "6-8" },
    image: "https://example.com/image11.jpg",
    discount: "50",
    description:
      "Admire breathtaking sea views from this cliffside villa on the Amalfi Coast with a stunning infinity pool.",
  },
  {
    name: "Coastal Escape Villa",
    address: { state: "Noosa", city: "Queensland", country: "Australia" },
    rating: 4.83,
    category: ["Beachfront", "Pet Friendly", "Free Parking"],
    price: 3400,
    offers: { bed: "3", shower: "3", occupants: "4-6" },
    image: "https://example.com/image12.jpg",
    discount: "",
    description:
      "Escape to Noosa’s coast in this beachfront villa that welcomes pets and offers tranquil sea breezes.",
  },
  {
    name: "Historical Villa",
    address: { state: "Florence", city: "Tuscany", country: "Italy" },
    rating: 4.67,
    category: ["Historical", "Free Breakfast", "Self Checkin"],
    price: 2700,
    offers: { bed: "2", shower: "2", occupants: "2-4" },
    image: "https://example.com/image13.jpg",
    discount: "35",
    description:
      "Stay in a centuries-old Tuscan villa that blends history with comfort, offering breakfast and easy self check-in.",
  },
  {
    name: "Downtown Apartment",
    address: { state: "Tokyo", city: "Tokyo", country: "Japan" },
    rating: 4.81,
    category: ["City Center", "Free WiFi", "Public Transport"],
    price: 2200,
    offers: { bed: "1", shower: "1", occupants: "2" },
    image: "https://example.com/image14.jpg",
    discount: "",
    description:
      "Modern apartment in downtown Tokyo with high-speed Wi-Fi and convenient access to public transport.",
  },
  {
    name: "Luxury Safari Lodge",
    address: { state: "Serengeti", city: "Mara", country: "Tanzania" },
    rating: 4.97,
    category: ["Safari", "Guided Tours", "Free Breakfast"],
    price: 4500,
    offers: { bed: "4", shower: "4", occupants: "6-8" },
    image: "https://example.com/image15.jpg",
    discount: "20",
    description:
      "Experience the wild in style at this luxury safari lodge offering guided tours and all-inclusive meals.",
  },
  {
    name: "Countryside Cottage",
    address: { state: "Cotswolds", city: "Gloucestershire", country: "UK" },
    rating: 4.58,
    category: ["Countryside", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: { bed: "2", shower: "1", occupants: "2-4" },
    image: "https://example.com/image16.jpg",
    discount: "25",
    description:
      "A charming countryside cottage in the Cotswolds featuring a cozy fireplace and rustic decor.",
  },
  {
    name: "Riverfront Mansion",
    address: { state: "Paris", city: "Île-de-France", country: "France" },
    rating: 4.86,
    category: ["Riverfront", "Private Garden", "Self Checkin"],
    price: 5000,
    offers: { bed: "4", shower: "3", occupants: "6-8" },
    image: "https://example.com/image17.jpg",
    discount: "30",
    description:
      "Luxury riverfront mansion in Paris with a private garden and spacious interiors for elegant stays.",
  },
  {
    name: "Ski Chalet",
    address: { state: "Zermatt", city: "Valais", country: "Switzerland" },
    rating: 4.75,
    category: ["Mountain View", "Ski Access", "Fireplace"],
    price: 3900,
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: "https://example.com/image18.jpg",
    discount: "",
    description:
      "Cozy ski chalet with direct access to slopes and panoramic views of the Swiss Alps.",
  },
  {
    name: "Island Paradise Villa",
    address: { state: "Mahe", city: "Victoria", country: "Seychelles" },
    rating: 4.98,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 6500,
    offers: { bed: "5", shower: "5", occupants: "8-10" },
    image: "https://example.com/image19.jpg",
    discount: "60",
    description:
      "A true island paradise featuring a private infinity pool, beach access, and personal chef services.",
  },
  {
    name: "Clifftop Retreat",
    address: { state: "Cape Town", city: "Western Cape", country: "South Africa" },
    rating: 4.78,
    category: ["Ocean View", "Private Pool", "Self Checkin"],
    price: 4100,
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: "https://example.com/image20.jpg",
    discount: "",
    description:
      "Spectacular clifftop villa with breathtaking Atlantic Ocean views, perfect for relaxation and luxury stays.",
  },
];
